### ISSUE TITLE
Github setup and contributions

### ISSUE THREAD

**Issue by colinscz** [six-group/six-webcomponents#3]
Hi everyone

Currently the setup for the six-webcomponents on Github is in progress. For the setup to be complete and fully working the following tasks are in progress:

- [x] CI/CD pipelines for release 🏗️ 👷🏽 💛  --> @colinscz  #4 
- [x] #33 https://github.com/six-group/six-webcomponents/pull/43 
- [x] Migrate remaining contributions from internal repository 🧑‍🏭  --> @johann-latocha #18 
- [x] Upgrade Stencil to v3 and corresponding dependencies --> @ibirrer #22 
- [x] Introduce strict typing -->  #44 

We will let you know once we have a clearer overview on when these tasks will be finished in 2023.

Once the setup is complete we will start addressing the first contributions. If you want to address certain things already please get in touch with the team internally and/or have a look at the current roadmap for version 4.0.0. Otherwise it could happen that certain contributions overlap until everything is fully migrated.

Thank you and best regards

SIX Webcomponents Team
